const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const cfg=window.GLOW_CONFIG,db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const wa=(p,m)=>`https://wa.me/${String(p||'').replace(/\D/g,'')}?text=${encodeURIComponent(m)}`;
$('#loginBtn').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error){$('#loginError').textContent='Revisa el correo y la contraseña.';return}show()};
$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};
$$('.tabs-admin button').forEach(b=>b.onclick=()=>{$$('.tabs-admin button').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active')});
async function show(){$('#login').classList.add('hidden');$('#dashboard').classList.remove('hidden');load()}
async function load(){const [tr,br,qr,or]=await Promise.all([db.from('test_results').select('*').order('created_at',{ascending:false}),db.from('bookings').select('*').order('created_at',{ascending:false}),db.from('questions').select('*').order('created_at',{ascending:false}),db.from('orders').select('*').order('created_at',{ascending:false})]);const t=tr.data||[],b=br.data||[],q=qr.data||[],o=or.data||[];$('#sTests').textContent=t.length;$('#sBookings').textContent=b.length;$('#sQuestions').textContent=q.length;$('#sOrders').textContent=o.length;
$('#tests').innerHTML='<h2>Glow Match recibidos</h2>'+(t.length?t.map(x=>`<div class="record"><div class="head"><div><b>${esc(x.client_name)} · ${esc(x.test_type)}</b><p>${esc(x.phone)}</p></div><span class="status">${x.reviewed?'Revisado':'Nuevo'}</span></div><p>${esc(x.recommendation)}</p><details><summary>Ver respuestas</summary><pre>${esc(JSON.stringify(x.answers,null,2))}</pre></details><div class="actions"><a target="_blank" href="${wa(x.phone,`Hola ${x.client_name} 💗 Soy Anthonia de Glow by Antho. Vi que realizaste nuestro Glow Match y quería orientarte sobre tu resultado.`)}">WhatsApp</a><button onclick="review('${x.id}')">Marcar revisado</button></div></div>`).join(''):'<p>Aún no hay tests.</p>');
$('#bookings').innerHTML='<h2>Reservas</h2>'+(b.length?b.map(x=>`<div class="record"><div class="head"><div><b>${esc(x.client_name)} — ${esc(x.service)}</b><p>${esc(x.appointment_date)} · ${esc(x.appointment_time)} · ${esc(x.phone)}</p></div><span class="status">${esc(x.status)}</span></div><p>Abono: $${Number(x.deposit_amount||0).toLocaleString('es-CL')}</p><div class="actions"><a target="_blank" href="${wa(x.phone,`Hola ${x.client_name} 💗 Recibí tu solicitud para ${x.service}.`)}">WhatsApp</a><button onclick="bookingStatus('${x.id}','confirmada')">Confirmar</button><button onclick="bookingStatus('${x.id}','realizada')">Realizada</button></div></div>`).join(''):'<p>Aún no hay reservas.</p>');
$('#questions').innerHTML='<h2>Preguntas</h2>'+(q.length?q.map(x=>`<div class="record"><b>${esc(x.client_name)} · ${esc(x.category)}</b><p>${esc(x.question)}</p><textarea id="a-${x.id}" placeholder="Escribe tu respuesta">${esc(x.answer||'')}</textarea><div class="actions"><button onclick="saveAnswer('${x.id}')">Guardar respuesta</button></div></div>`).join(''):'<p>Aún no hay preguntas.</p>');
$('#orders').innerHTML='<h2>Pedidos</h2>'+(o.length?o.map(x=>`<div class="record"><div class="head"><div><b>Pedido #${x.order_number||'—'} · ${esc(x.client_name)}</b><p>${esc(x.phone)} · ${esc(x.commune)} · ${esc(x.starken_destination)}</p></div><span class="status">${esc(x.payment_status)}</span></div><pre>${esc(JSON.stringify(x.items,null,2))}</pre><p>Total: $${Number(x.products_total||0).toLocaleString('es-CL')}</p><div class="actions"><a target="_blank" href="${wa(x.phone,`Hola ${x.client_name} 💗 Recibí tu pedido Glow by Antho.`)}">WhatsApp</a><button onclick="orderStatus('${x.id}','pago_confirmado','preparando')">Pago recibido</button><button onclick="orderStatus('${x.id}','pago_confirmado','enviado')">Enviado</button></div></div>`).join(''):'<p>Aún no hay pedidos.</p>')}
window.review=async id=>{await db.from('test_results').update({reviewed:true}).eq('id',id);load()};window.bookingStatus=async(id,status)=>{await db.from('bookings').update({status}).eq('id',id);load()};window.saveAnswer=async id=>{await db.from('questions').update({answer:$('#a-'+id).value,status:'respondida',answered_at:new Date().toISOString()}).eq('id',id);load()};window.orderStatus=async(id,payment_status,shipping_status)=>{await db.from('orders').update({payment_status,shipping_status}).eq('id',id);load()};
(async()=>{const {data}=await db.auth.getSession();if(data.session)show()})();
